// frontend-react/src/components/player/PlayerCore.tsx
import {Box} from '@mui/material'
import {useEffect, useState, useRef} from 'react'
import {getMusicDetail} from '@/api/music'
import {musicBus, MusicBusEvents, MusicItem} from '@/enum'
import {observer} from 'mobx-react-lite'
import {musicStore} from '@/store'
import {toast} from 'react-toastify'
import {useDidUpdateEffect} from '@/utils/hooks'

const originalTitle = document.title
const updateTitle = (title, isPaused = false) => {
  if (!title) {
    document.title = originalTitle
  } else {
    document.title = `${isPaused ? '⏸️' : '▶️'} ${title}`
  }
}

const PlayerCore = () => {
  const [mStore] = useState(musicStore)
  const audioEl = useRef(null)

  useEffect(() => {
    const audio = audioEl.current
    // console.log('audioEl', audioEl.current)

    if ('mediaSession' in navigator) {
      navigator.mediaSession.setActionHandler('play', play)
      navigator.mediaSession.setActionHandler('pause', pause)
    }

    audio.addEventListener('play', () => {
      mStore.setPaused(false)
    })

    audio.addEventListener('pause', () => {
      mStore.setPaused(true)
    })

    audio.addEventListener('ended', () => {
      console.log('ended!!')
      mStore.setPaused(true)
    })

    audio.addEventListener('canplay', (evt) => {
      mStore.setDuration(evt.target.duration)
    })

    audio.addEventListener('timeupdate', (evt) => {
      mStore.setCurrentTime(evt.target.currentTime)
    })

    audio.addEventListener('error', (error) => {
      toast.error('音频加载失败！', {
        position: 'top-center',
        autoClose: 3000,
      })
      console.error(error)
    })

    musicBus.on(MusicBusEvents.PLAY, play)
    musicBus.on(MusicBusEvents.PAUSE, pause)
    musicBus.on(MusicBusEvents.SET_CURRENT_TIME, setCurrentTime)
  }, [])

  useEffect(() => {
    handleCurrentSong(mStore.currentSong)
  }, [mStore.currentSong])

  useDidUpdateEffect(() => {
    if (mStore.currentSong) {
      updateTitle(mStore.currentSong.filenameDisplay, mStore.paused)
    }
  }, [mStore.paused])

  const setAudioSource = (src) => {
    pause()
    setTimeout(() => {
      if (!src) {
        audioEl.current.removeAttribute('src')
        return
      }
      audioEl.current.src = src
    })
  }

  const handleCurrentSong = async (item: MusicItem) => {
    console.log('handleCurrentSong', item)
    if (!item || !item.filename) {
      updateTitle('', true)
      setAudioSource(null)
      return
    }
    updateTitle(item.filenameDisplay)
    setAudioSource(item.getSource())
    if (!item.isOutSource) {
      const params = {
        path: item.path,
        filename: item.filename,
        updatePlayStat: true,
      }
      if (!item.isDetailLoaded) {
        const detail: any = await getMusicDetail(params)
        // console.log('detail', detail)

        const {metadata, cover, lyric} = detail
        item.setMetadata(metadata, cover, lyric)
        updateTitle(item.filenameDisplay)
      } else {
        // only update play status
        await getMusicDetail({
          ...params,
          updateStatOnly: true,
        })
      }
    }

    // https://developers.google.com/web/updates/2017/02/media-session
    if ('mediaSession' in navigator) {
      let artwork = [
        {src: require('@/assets/images/default-cover.jpg'), sizes: '512x512'},
      ]
      if (item.cover) {
        artwork = [{src: item.cover, sizes: '512x512'}]
      }

      /* eslint-disable no-undef */
      navigator.mediaSession.metadata = new MediaMetadata({
        /* eslint-enable no-undef */
        title: item.title,
        artist: item.artist,
        album: item.album,
        artwork,
      })
    }
  }

  const play = () => {
    audioEl.current.play()
  }
  const pause = () => {
    audioEl.current.pause()
  }
  const setCurrentTime = (val) => {
    audioEl.current.currentTime = val
  }

  return (
    <Box sx={{position: 'fixed', bottom: '10%', right: '10%', zIndex: 100000}}>
      <audio ref={audioEl} controls />
    </Box>
  )
}

export default observer(PlayerCore)

// frontend/src/components/PlayerCore.vue
<template>
  <div class="player-core">
    <audio
        v-show="false"
        :ref="setAudioRef"
        :src="source" controls></audio>
  </div>
</template>

<script lang="ts">
import {computed, defineComponent, onBeforeUnmount, onMounted, watch} from 'vue'
import {MusicItem} from "@/enum";
import bus, {
  ACTION_CHANGE_CURRENT_TIME,
  ACTION_NEXT,
  ACTION_PLAY_ENDED,
  ACTION_PREV,
  ACTION_TOGGLE_PLAY,
  ACTION_CHANGE_VOLUME
} from "@/utils/bus";
import store from '@/store'
import {getDetail} from "@/api/music.ts";

export default defineComponent({
  name: "PlayerCore",
  setup() {
    let audio
    const setAudioRef = (el) => {
      audio = el
    }

    const musicItem = computed((): MusicItem => {
      return store.getters.musicItem
    })

    const updateTitle = (musicItem: MusicItem, isPaused?: boolean) => {
      document.title = `${isPaused ? '⏸️' : '▶️'} ${musicItem.filenameDisplay}`
    }

    watch(musicItem, async (val) => {
      // console.log('musicItem changed', val)

      updateTitle(val)

      const params = {
        path: val.path,
        filename: val.filename,
        updatePlayStat: true
      }
      if (!val.isDetailLoaded) {
        const detail = await getDetail(params)
        // console.log('detail', detail)

        const {
          metadata,
          cover,
          lyric
        } = detail
        val.setMetadata(metadata, cover, lyric)
        updateTitle(val)
      } else {
        // only update play status
        await getDetail({
          ...params,
          updateStatOnly: true
        })
      }

      // https://developers.google.com/web/updates/2017/02/media-session
      if ('mediaSession' in navigator) {
        let artwork: Array<any> = [{ src: require('@/assets/images/no-image.jpg'), sizes: '512x512' }]
        if (val.cover) {
          artwork = [
            { src: val.cover, sizes: '512x512' },
          ]
        }

        /* eslint-disable no-undef */
        // @ts-ignore
        navigator.mediaSession.metadata = new MediaMetadata({
          /* eslint-enable no-undef */
          title: val.title,
          artist: val.artist,
          album: val.album,
          artwork
        })
      }

    })
    const source = computed((): string | null => {
      return musicItem.value.getSource() || null
    })

    const paused = computed({
      get(): boolean {
        return store.getters.paused
      },
      set(value: boolean) {
        store.commit('setPaused', value)
      }
    })

    watch(paused, (val) => {
      updateTitle(musicItem.value, val)
    })

    const play = () => {
      audio.play()
    }
    const pause = () => {
      audio.pause()
    }
    const previous = () => {
      bus.emit(ACTION_PREV)
    }
    const next = () => {
      bus.emit(ACTION_NEXT)
    }
    const togglePlay = () => {
      if (!audio) {
        return
      }
      if (audio.paused) {
        play()
      } else {
        pause()
      }
    }
    const registerAudioEvents = (audio) => {
      if ('mediaSession' in navigator) {
        // @ts-ignore
        navigator.mediaSession.setActionHandler('play', play);
        // @ts-ignore
        navigator.mediaSession.setActionHandler('pause', pause);
        // navigator.mediaSession.setActionHandler('seekbackward', function() {});
        // navigator.mediaSession.setActionHandler('seekforward', function() {});
        // @ts-ignore
        navigator.mediaSession.setActionHandler('previoustrack', previous);
        // @ts-ignore
        navigator.mediaSession.setActionHandler('nexttrack', next);
      }

      audio.addEventListener('play', () => {
        paused.value = false
      })

      audio.addEventListener('pause', () => {
        paused.value = true
      })

      audio.addEventListener('ended', () => {
        bus.emit(ACTION_PLAY_ENDED)
      })

      audio.addEventListener('canplay', (evt) => {
        // console.log('canplay', audio)
        store.commit('setDuration', evt.target.duration)
      })

      audio.addEventListener('timeupdate', (evt) => {
        // console.log('timeupdate', evt.target.currentTime)
        store.commit('setCurrentTime', evt.target.currentTime)
      })

      audio.addEventListener('error', (error) => {
        window.$notify.error('Load fail or no supported source')
        console.error(error)
      })
    }
    const changeCurrentTime = (newTime) => {
      audio && (audio.currentTime = newTime)
    }

    const changeVolume = (val) => {
      audio && (audio.volume = val/100)
    }

    onMounted(() => {
      bus.on(ACTION_TOGGLE_PLAY, togglePlay)
      bus.on(ACTION_CHANGE_CURRENT_TIME, changeCurrentTime)
      bus.on(ACTION_CHANGE_VOLUME, changeVolume)

      registerAudioEvents(audio)
    })
    onBeforeUnmount(() => {
      bus.off(ACTION_TOGGLE_PLAY, togglePlay)
      bus.off(ACTION_CHANGE_CURRENT_TIME, changeCurrentTime)
      bus.off(ACTION_CHANGE_VOLUME, changeVolume)
    })

    return {
      audio,
      musicItem,
      source,
      paused,
      setAudioRef,
      togglePlay,
      play,
      pause
    }
  }
})
</script>

<style lang="scss" scoped>
.player-core {
  position: fixed;
  z-index: 90;
  right: 10px;
  bottom: 80px;
}
</style>
